# Generated by Django 5.2 on 2025-04-21 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_alter_experience_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='start_date',
        ),
    ]
