# Generated by Django 5.2 on 2025-04-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_remove_education_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='grade',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
