# Generated by Django 5.2 on 2025-04-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_info_projectenglish_name_projectgerman_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='alternative_value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
