# Generated by Django 5.2 on 2025-04-21 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_info_alternative_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='alternative_value',
        ),
        migrations.RemoveField(
            model_name='info',
            name='key',
        ),
        migrations.RemoveField(
            model_name='info',
            name='value',
        ),
        migrations.AddField(
            model_name='info',
            name='internal_tag',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='InfoEnglish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('value', models.TextField()),
                ('alternative_value', models.TextField(blank=True, null=True)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.info')),
            ],
        ),
        migrations.CreateModel(
            name='InfoGerman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('value', models.TextField()),
                ('alternative_value', models.TextField(blank=True, null=True)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.info')),
            ],
        ),
    ]
