# Generated by Django 5.2 on 2025-04-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_remove_info_alternative_value_remove_info_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infogerman',
            name='key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='infogerman',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
