# Generated by Django 5.2 on 2025-04-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_alter_infogerman_key_alter_infogerman_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_tag', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
    ]
