# Generated by Django 5.2 on 2025-06-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_coverletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
    ]
